image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Setup PostgreSQL and Rails"
    init: |
      # Install RVM and the specific Ruby version
      curl -sSL https://get.rvm.io | bash -s stable
      source /home/gitpod/.rvm/scripts/rvm
      rvm install 3.2.2
      rvm use 3.2.2 --default

      # Initialize PostgreSQL without password prompt
      sudo service postgresql start
      psql -U postgres -c "CREATE USER chatwoot_user WITH PASSWORD 'password';" || true
      psql -U postgres -c "CREATE DATABASE chatwoot_dev OWNER chatwoot_user;" || true
      psql -U postgres -c "CREATE DATABASE chatwoot_test OWNER chatwoot_user;" || true
      psql -U postgres -c "ALTER USER chatwoot_user CREATEDB;" || true
      cp config/database.example.yml config/database.yml
      sed -i 's/username:.*/username: chatwoot_user/' config/database.yml
      sed -i 's/password:.*/password: password/' config/database.yml
      gem install bundler -v 2.4.6
      bin/setup
      yarn install
    command: bin/rails server -b 0.0.0.0

ports:
  - port: 3000
    onOpen: open-preview
