image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Setup and Start Services"
    init: |
      # Install RVM and the specific Ruby version
      curl -sSL https://get.rvm.io | bash -s stable
      source /home/gitpod/.rvm/scripts/rvm
      rvm install 3.2.2
      rvm use 3.2.2 --default

      # Initialize PostgreSQL and set up user and database
      sudo service postgresql start
      sudo -u postgres psql --command "DROP DATABASE IF EXISTS chatwoot_dev;"
      sudo -u postgres psql --command "DROP DATABASE IF EXISTS chatwoot_test;"
      sudo -u postgres psql --command "DROP USER IF EXISTS chatwoot_user;"
      sudo -u postgres psql --command "CREATE USER chatwoot_user WITH PASSWORD 'password';"
      sudo -u postgres psql --command "CREATE DATABASE chatwoot_dev OWNER chatwoot_user;"
      sudo -u postgres psql --command "CREATE DATABASE chatwoot_test OWNER chatwoot_user;"
      sudo -u postgres psql --command "ALTER USER chatwoot_user CREATEDB;"
      cp config/database.example.yml config/database.yml
      sed -i 's/username:.*/username: chatwoot_user/' config/database.yml
      sed -i 's/password:.*/password: password/' config/database.yml
      gem install bundler -v 2.4.6
      bin/setup
      yarn install
    command: bin/rails server -b 0.0.0.0

ports:
  - port: 3000
    onOpen: open-preview
