image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Setup and Start"
    init: |
      sudo apt update
      sudo apt install -y postgresql postgresql-contrib libpq-dev
      sudo service postgresql start
      sudo -u postgres psql -c "CREATE USER chatwoot_user WITH PASSWORD 'password';" || true
      sudo -u postgres psql -c "CREATE DATABASE chatwoot_dev OWNER chatwoot_user;" || true
      sudo -u postgres psql -c "CREATE DATABASE chatwoot_test OWNER chatwoot_user;" || true
      sudo -u postgres psql -c "ALTER USER chatwoot_user CREATEDB;" || true
      cp config/database.example.yml config/database.yml
      sed -i 's/username:.*/username: chatwoot_user/' config/database.yml
      sed -i 's/password:.*/password: password/' config/database.yml
      bin/setup
      yarn install
    command: |
      bin/rails server -b 0.0.0.0

ports:
  - port: 3000
    onOpen: open-preview
