default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>
  pool: <%= Sidekiq.server? ? ENV.fetch('SIDEKIQ_CONCURRENCY', 10) : ENV.fetch('RAILS_MAX_THREADS', 5) %>
  variables:
    statement_timeout: <%= ENV.fetch('POSTGRES_STATEMENT_TIMEOUT', '14s') %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'chatwoot_dev') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'chatwoot_user') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'password') %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'chatwoot_test') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'chatwoot_user') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'password') %>

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'chatwoot_production') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'chatwoot_prod') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'chatwoot_prod') %>
